-- Table: USERS (user là từ khóa SQL, nên đổi tên)
CREATE TABLE IF NOT EXISTS USERS (
    id SERIAL PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

-- Table: COORDINATES
CREATE TABLE IF NOT EXISTS COORDINATES (
    id SERIAL PRIMARY KEY,
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL
);

-- Table: LOCATION
CREATE TABLE IF NOT EXISTS LOCATION (
    id SERIAL PRIMARY KEY,
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    z DOUBLE PRECISION NOT NULL,
    location_name TEXT
);

-- Table: PERSON
CREATE TABLE IF NOT EXISTS PERSON (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    coordinates_id INT REFERENCES COORDINATES(id) ON DELETE CASCADE,
    creation_date TIMESTAMP NOT NULL,
    height DOUBLE PRECISION CHECK (height > 0),
    birthday TIMESTAMP,
    eye_color TEXT,
    hair_color TEXT,
    location_id INT REFERENCES LOCATION(id) ON DELETE CASCADE,
    user_id INT REFERENCES USERS(id) ON DELETE CASCADE
);